dekoding_test/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('root.urls')),
    path('admin/', admin.site.urls),
]

root/urls.py
from django.urls import path
from . import views

from .views import (
    IndexView,
    FrontendView,
    BackendView,
    DogListView,
    dogAddView,
    OwnerListView,
    ownerAddView
)


urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('frontend/', FrontendView.as_view(), name="frontend"),
    path('backend/', BackendView.as_view(), name="backend"),
    path('dog/list', DogListView.as_view(), name="doglist"),
    path('dog/add', views.dogAddView, name="dogadd"),
    path('owner/list', OwnerListView.as_view(), name="ownerlist"),
    path('owner/add', views.ownerAddView, name="owneradd"),
    
]

root/models.py
from django.db import models

class DogModel(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField()
    breed = models.CharField(max_length=50)
    owner = models.CharField(max_length=50)

    def addDog(self,name,age,breed,owner):
        self.name = name
        self.age = age
        self.breed = breed
        self.owner = owner
        self.save()

    def __str__(self):
        return self.name


class OwnerModel(models.Model):
    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=9)
    address = models.CharField(max_length=100)

    def addOwner(self,name,phone,address):
        self.name = name
        self.phone = phone
        self.address = address
        self.save()

    def __str__(self):
        return self.name

root/forms.py
from django import forms
from .models import DogModel, OwnerModel

class DogModelForm(forms.ModelForm):

    class Meta:
        model = DogModel
        fields = ('name', 'breed', 'age', 'owner')


class OwnerModelForm(forms.ModelForm):

    class Meta:
        model = OwnerModel
        fields = ('name', 'phone', 'address')

root/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .models import DogModel, OwnerModel
from .forms import DogModelForm, OwnerModelForm

class IndexView(View):
    template_name = "index.html"

    def get(self, request):
        context = {}

        return render(request, self.template_name, context)


class FrontendView(View):
    template_name = "frontend.html"

    def get(self, request):
        context = {}

        return render(request, self.template_name, context)


class BackendView(View):
    template_name = "backend.html"

    def get(self, request):
        context = {}

        return render(request, self.template_name, context)


#Dog Views

class DogListView(View):
    template_name = "./dog/list.html"

    def get(self, request):
        dogs = DogModel.objects.all()
        return render(request, self.template_name, {'dogs': dogs})


def dogAddView(request):
    if request.method == "POST":
        form = DogModelForm(request.POST)
        if form.is_valid():
            dog = form.save(commit=False)
            dog.name = request.POST.get('name')
            dog.age = request.POST.get('age')
            dog.breed = request.POST.get('breed')
            dog.owner = request.POST.get('owner')
            dog.save()
            return redirect('/dog/add')
                
    else:
        form = DogModelForm()
    return render(request, "./dog/add.html" , {'form': form})


#Owner Views
class OwnerListView(View):
    template_name = "./owner/list.html"

    def get(self, request):
        print("AQUIIIII 1")
        owners = OwnerModel.objects.all()
        return render(request, self.template_name, {'owners': owners})


def ownerAddView(request):
    if request.method == "POST":
        form = OwnerModelForm(request.POST)
        if form.is_valid():
            owner = form.save(commit=False)
            owner.name = request.POST.get('name')
            owner.phone = request.POST.get('phone')
            owner.address = request.POST.get('address')
            owner.save()
            return redirect('/owner/add')
                
    else:
        form = OwnerModelForm()
    return render(request, "./owner/add.html" , {'form': form})

templates/backend.html
{% load static %}

<!DOCTYPE html>
<html lang="en" style="height: 100%">
<head>
  <meta charset="UTF-8">
  <title>Dekoding Test - BackEnd</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
        integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  </head>
<body style="padding: 0; height: 100%">
  <div class="row" style="height: 100%">
    <div class="col-md-2" style="background-color:rgb(31,31,32)">
       
      <div class="logo">
        <a class="simple-text" href="#">
          <div class="logo-img">
            <img src="{% static 'images/small_logo.png' %}" class="img-fluid" width="25px" />
          </div>
          DEKODING
        </a> 
      </div>
      <hr align=center width=90% color=white style="margin-top:0;height: 1px"> 

      <ul class="nav">
        <li class="nav-item col-md-12">
          <a class="nav-link col-md-12" href="{% url 'doglist' %}">
            <img src="{% static 'images/list_icon.png' %}" class="nav-icon" />
            <p>Dog List</p>
          </a>
        </li>
        <li class="nav-item col-md-12">
          <a class="nav-link col-md-12" href="{% url 'dogadd' %}">
            <img src="{% static 'images/add_icon.png' %}" class="nav-icon" />
            <p>Add Dog</p>
          </a>
        </li>
        <li class="nav-item col-md-12">
          <a class="nav-link col-md-12" href="{% url 'ownerlist' %}">
            <img src="{% static 'images/list_icon.png' %}" class="nav-icon" />
            <p>Owner List</p>
          </a>
        </li>
        <li class="nav-item col-md-12">
          <a class="nav-link col-md-12" href="{% url 'owneradd' %}">
            <img src="{% static 'images/add_icon.png' %}" class="nav-icon" />
            <p>Add Owner</p>
          </a>
        </li>
      </ul>
    </div>

        <div class="col-md-10" style="height:100%;padding-right:30px;padding-left:20px;padding-top: 80px;background-color: rgb(238,238,238);">    
          {% block content %}{% endblock %}
        </div>
  </div>


<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Dekoding Test</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
        integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">
    <img src="{% static 'images/dekoding_logo.png' %}" class="img-fluid" width="100px">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
{% block content %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/dog/add.html
{% extends "backend.html" %}
{% load static %}

{% block content %}
<div class="row" >
  <div class="col-md-8">
    <div class="card">
      <div class="card-header-list">
        <h4 class="card-title ">Add Dog</h4>
      </div>
      <div class="card-body">
        <form method="post" action="{% url 'dogadd' %}"> {% csrf_token %}
          <div class="row">
            <div class="col-md-5">
                <label for="id_name" class="inp">
                    <input type="text" id="id_name" name="name" placeholder="&nbsp;">
                    <span class="label">Name</span>
                    <span class="border"></span>
                </label>
            </div>
          </div>

          <div class="row">
              <div class="col-md-4">
                  <label for="breed" class="inp">
                      <input type="text" id="breed" name="breed" placeholder="&nbsp;">
                      <span class="label">Breed</span>
                      <span class="border"></span>
                  </label>
              </div>
              <div class="col-md-4">
                  <label for="age" class="inp">
                      <input type="text" name="age" id="age" placeholder="&nbsp;">
                      <span class="label">Age</span>
                      <span class="border"></span>
                  </label>
              </div>
              <div class="col-md-4">
                  <label for="owner" class="inp">
                      <input type="text" name="owner" id="owner" placeholder="&nbsp;">
                      <span class="label">Owner</span>
                      <span class="border"></span>
                  </label>
              </div>
              
            </div>
            <button type="submit" class="btn-save-dog col-md-2">SAVE DOG</button>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/dog/list.html
{% extends "backend.html" %}
{% load static %}

{% block content %}
<div class="row" >
  <div class="col-md-12">
    <div class="card">
      <div class="card-header-list">
        <h4 class="card-title ">Dogs List</h4>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class="text-primary-list">
              <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Breed</th>
                <th>Owner</th>
              </tr>
            </thead>
            <tbody>
              {% for dog in dogs %}
              <tr>
                <td>{{ dog.name }}</td>
                <td>{{ dog.age }}</td>
                <td>{{ dog.breed }}</td>
                <td>{{ dog.owner }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/frontend.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="front-end-test">
    <meta name="author" content="Paula Del Carpio">

    <title>Front End Test by Paula Del Carpio</title>

    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">

    <!-- Additional Custom styles -->
    <style>
    .carousel-item {
        height: 100vh;
        min-height: 350px;
        background: no-repeat center center scroll;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
    .carousel-control-container {
        width: 7%;
    }
    .carousel-control-span {
        width: 50px;
        height: 50px;
    }
    .second-slide-letter-format {
        font-size: 10rem;
        text-align: center;
        color: black;
        vertical-align: middle;
    }
    .second-slide-letter-container {
        text-align:center;
        height: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .third-slider-container {
        background-color: rgb(0,123,255);
        border-radius: 10px;
        text-align: center;
        justify-content: center;
        margin-top:25px;
        color: white;
    }
    .show{
        display: inline-block;
    }
    </style>
  </head>

  <body>
    <header>
        <div id="carouselExampleIndicators" class="carousel slide" data-interval="false">
          <div class="carousel-inner" role="listbox">

            <!-- First Slider Item - Centered logo of Dekoding with a solid color background -->
            <div class="carousel-item active" style="background-color: rgb(96,96,96)">
              <div class="row" style="height:100%" >
                <div class="col-md-3" > </div>
                <img src="{% static 'images/logo.png' %}" class="col-md-6 img-responsive center-block my-auto"  />
                <div class="col-md-3" > </div>
              </div>
            </div>

            <!-- Second Slider Item - Letters -->
            <div class="carousel-item" >
              <!-- First Row -->
              <div class="row" style="height:51%" >
                <div class="col-md-4 second-slide-letter-container" style="background-color: rgb(41,171,226);">
                    <p class="second-slide-letter-format">D</p>
                </div>
                <div class="col-md-4 second-slide-letter-container" style="background-color: rgb(0,113,188);">
                    <p class="second-slide-letter-format">E</p>
                </div>
                <div class="col-md-4 second-slide-letter-container" style="background-color: rgb(46,49,146);">
                    <p class="second-slide-letter-format">K</p>
                </div>    
              </div>
              <!-- Second Row -->
              <div class="row" style="height:49%;background-color: rgb(83,71,65)" >
                <span class="col-md-12 second-slide-letter-format my-auto">ODING</span>                 
              </div>
            </div>

            <!-- Third Slider Item - Modal -->
            <div class="carousel-item" style="background-image: url({% static 'images/wallpaper.png' %})">
              <div class="row" style="height: 50%"> </div>
              <div class="row" style="height: 50%">
                <div class="col-md-6"></div>
                <div class="col-md-6 " style="height: 100%;padding-right:80px;padding-left: 28px;" >
                  <div class="col-md-12 third-slider-container" style="width:100%;height:70%;font-size: 3em">Dekoding</div>
                  <button type="button" data-toggle="modal" data-target="#modal1" class="col-md-3 float-right btn btn-primary" style="font-size: 1.2em; border-radius:10px;margin-top:20px">Submit</button>
                </div>
              </div>
            </div>

          </div>
          <a class="carousel-control-prev carousel-control-container" href="#carouselExampleIndicators" role="button" data-slide="prev" >
            <span class="carousel-control-prev-icon carousel-control-span" aria-hidden="true" ></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next carousel-control-container" href="#carouselExampleIndicators" role="button" data-slide="next" >
            <span class="carousel-control-next-icon carousel-control-span" aria-hidden="true"  ></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
        
        <!-- Modal -->
        <div class="modal fade" id="modal1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-sm" style="max-width: 350px;">
            <div class="modal-content" style="border-radius: 10px;">
              <div class="modal-header" style="padding: 7px">
                <h5 class="modal-title" id="modalLabel" style="font-size:0.8em;padding:4px">Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="padding-top:7px">
                  <span aria-hidden="true" style="font-size:0.7em;color: rgb(194,194,200)">&times;</span>
                </button>
              </div>
              <div class="modal-body" style="font-size:0.6em;margin-bottom: 40px">Content Content</div>
              <div class="modal-footer" style="padding: 5px;border-top: 0px;">
                <button type="button" class="btn btn-secondary" style="font-size:0.7em;display:none;" id="btnCloseModal" onclick="closeModal()" >Close</button>
                <button type="button" class="btn btn-primary" style="font-size:0.7em" id="btnSubmitModal" onclick="submitModal()" >Submit</button>
              </div>
            </div>
          </div>
        </div>
      </header>

    <!-- Additional JavaScript - Modal Functions-->
    <script>
        function submitModal(){
            var btnClose = document.getElementById("btnCloseModal");
            btnClose.style.display = "block";
        }
        function closeModal(){
            var btnClose = document.getElementById("btnCloseModal");
            btnClose.style.display = "none";
        }
    </script>
    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" ></script>

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <main role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Dekoding Test</h1>
        <p>This tests is all about testing your skills as Frontend and Backend developer, you should implement the tasks mentioned on the
          description of the test on the following views using bootstrap as UI.</p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-6">
          <h2>Frontend</h2>
          <p>We are going to test if you can create user interfaces according to the design sent.</p>
          <p><a class="btn btn-secondary" href="{% url 'frontend' %}" role="button">Lets do it »</a></p>
        </div>
        <div class="col-md-6">
          <h2>Backend</h2>
          <p>We are going to test if you can implement new functionalities to projects.</p>
          <p><a class="btn btn-secondary" href="{% url 'backend' %}" role="button">Lets do it »</a></p>
        </div>
      </div>
      <hr>
    </div> <!-- /container -->
  </main>
{% endblock %}

templates/owner/add.html
{% extends "backend.html" %}
{% load static %}

{% block content %}
<div class="row" >
  <div class="col-md-8">
    <div class="card">
      <div class="card-header-list">
        <h4 class="card-title ">Add Owner</h4>
      </div>
      <div class="card-body">
        <form method="post" action="{% url 'owneradd' %}"> {% csrf_token %}
          <div class="row">
            <div class="col-md-5">
                <label for="id_name" class="inp">
                    <input type="text" id="id_name" name="name" placeholder="&nbsp;">
                    <span class="label">Name</span>
                    <span class="border"></span>
                </label>
            </div>
          </div>

          <div class="row">
              <div class="col-md-4">
                  <label for="phone" class="inp">
                      <input type="text" id="phone" name="phone" placeholder="&nbsp;">
                      <span class="label">Phone Number</span>
                      <span class="border"></span>
                  </label>
              </div>
              <div class="col-md-4">
                  <label for="address" class="inp">
                      <input type="text" name="address" id="id_address" placeholder="&nbsp;">
                      <span class="label">Address</span>
                      <span class="border"></span>
                  </label>
              </div>
              
            </div>
            <button type="submit" class="btn-save-dog col-md-2">SAVE OWNER</button>
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/owner/list.html
{% extends "backend.html" %}
{% load static %}

{% block content %}
<div class="row" >
  <div class="col-md-12">
    <div class="card">
      <div class="card-header-list">
        <h4 class="card-title ">Owners List</h4>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class="text-primary-list">
              <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
              </tr>
            </thead>
            <tbody>
              {% for owner in owners %}
              <tr>
                <td>{{ owner.name }}</td>
                <td>{{ owner.phone }}</td>
                <td>{{ owner.address }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>
</div>
{% endblock %}